# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b4e58a22f91c4ec4871711c03fabd45"
name = "conf-page-survey"
handle = "conf-page-survey"
application_url = "https://via-milton-prayers-launched.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dawn-customized-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://via-milton-prayers-launched.trycloudflare.com/auth/callback",
  "https://via-milton-prayers-launched.trycloudflare.com/auth/shopify/callback",
  "https://via-milton-prayers-launched.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
